### ISSUE TITLE
Auto create partitions

### ISSUE THREAD

**Issue by rehanvdm** [rehanvdm/serverless-website-analytics#2]
- A cron to run at the beginning of each month that adds the new partitions
- A CFN custom resource to run if changing the sites

**Comment by m-radzikowski** [comment]
I've only briefly looked into the code, but here is a suggestion that may or may not make sense.

I see you have [3 partitions](https://github.com/rehanvdm/serverless-website-analytics/blob/44121366a2e8ca8773e2d73294ad2cd6ce76c0c4/src/backendAnalytics.ts#L102): `site`, `year`, and `month`.

For year and month, you can use [partition projection](https://docs.aws.amazon.com/athena/latest/ug/partition-projection.html). There is even a specific type for [dates](https://docs.aws.amazon.com/athena/latest/ug/partition-projection-supported-types.html#partition-projection-date-type). Then you don't need to update partitions, Athena will know that there may exist `year` partitions, let's say from 2023 to 2099. And `month` partitions from 1 to 12.

`site` is more tricky. But it's also less common change that can be done manually. With dynamic partitions, you can use enum type, if possible sites are given in Swa config (I'm not sure about it). Otherwise, I see there is also an "injected type", but I did not use it and don't know exactly how it works.

Again, great job with this project!

**Comment by rehanvdm** [comment]
That is a great idea! Completely slipped my mind. I will explore this, thanks for the suggestion.

Regarding `site` that can easily be managed via a Custom Resource in the CDK. So it will then create/update/delete the site partition whenever it gets added, so a once-off. Then the date partitions are dynamic which means no more partition creating 🙂. Definitely going to look into this one. Thanks again.

**Comment by rehanvdm** [comment]
Released in v.0.0.5, thanks @m-radzikowski! I could delete a lot of code 😃
